@startuml
class Dataloader{
    SRC : data.Field
    TGT : data.Field
    ~save_dataloader()
    +load_translation()
}

class Trainer{
    model
    optimizer
    criterion
    ~valid_epoch()
    ~train_epoch()
    ~save_model()
    ~lr_step_update()
    +train()
}

class Translator{
    dl : Dataloader
    model
    ~load_model()
    ~greedy_search()
    +translate()
}

 Translator *-- Dataloader

@enduml